name: Run checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2